export const environment = {
  production: false,
  api: {
    baseUrl: 'http://localhost:3000/api',
    authUrl: 'http://localhost:3000/api/auth',
    profileUrl: 'http://localhost:3000/api/profile',
    transactionUrl: 'http://localhost:3000/api/transactions',
    timeout: 2000,
    retryAttempts: 3,
    retryDelay: 1000,
  },
  features: {
    enableDebugMode: true,
    enablePerformanceMonitoring: true,
    enableStatePersistence: true,
    enableAutoSave: true,
    maxConcurrentRequests: 5,
    cacheEnabled: true,
    cacheTTL: 300000,
    optimisticUpdates: true,
  },
  auth: {
    tokenKey: 'auth_token',
    refreshTokenKey: 'refresh_token',
    sessionKey: 'user_session',
    tokenExpirationBuffer: 300000,
    autoRefreshEnabled: true,
    sessionTimeout: 1800000,
  },
  logging: {
    level: 'debug',
    enableConsole: true,
    enableRemote: false,
    remoteEndpoint: '',
    logActions: true,
    logStateChanges: true,
    logHttpRequests: true,
    logPerformanceMetrics: true,
  },
  performance: {
    enableWebVitals: true,
    reportInterval: 5000,
    metricsToTrack: ['FCP', 'LCP', 'FID', 'CLS', 'TTFB'],
    maxMetricsBuffer: 50,
    enableLongTaskDetection: true,
    longTaskThreshold: 50,
  },
  state: {
    persistenceKey: 'portal_state',
    blacklist: ['router', 'loading'],
    whitelist: ['auth', 'profile', 'transaction'],
    syncInterval: 60000,
    enableDevTools: true,
    maxHistorySize: 50,
  },
  user: {
    maxActiveUsers: 10000,
    sessionWarningTime: 120000,
    idleTimeout: 300000,
    maxLoginAttempts: 5,
    lockoutDuration: 900000,
  },
  ui: {
    theme: 'light',
    language: 'es',
    currency: 'COP',
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandSeparator: '.',
  },
  security: {
    enableCsrfProtection: true,
    enableXssProtection: true,
    enableContentSecurityPolicy: true,
    allowedDomains: ['localhost:3000', 'localhost:4200'],
  },
  analytics: {
    enabled: true,
    trackPageViews: true,
    trackEvents: true,
    trackErrors: true,
    sampleRate: 100,
  },
  errorHandling: {
    showDetailedErrors: true,
    enableErrorBoundary: true,
    maxRetries: 3,
    retryableStatusCodes: [408, 429, 500, 502, 503, 504],
    fallbackMessage: 'Ha ocurrido un error. Por favor, intente de nuevo.',
  },
  notifications: {
    enabled: true,
    position: 'top-right',
    duration: 5000,
    maxVisible: 3,
    types: {
      success: { duration: 3000, icon: true },
      error: { duration: 8000, icon: true },
      warning: { duration: 5000, icon: true },
      info: { duration: 4000, icon: true },
    },
  },
};

export type EnvironmentConfig = typeof environment;