export const environment = {
  production: true,
  api: {
    baseUrl: 'https://api.portalautogestion.com/api',
    authUrl: 'https://api.portalautogestion.com/api/auth',
    profileUrl: 'https://api.portalautogestion.com/api/profile',
    transactionUrl: 'https://api.portalautogestion.com/api/transactions',
    timeout: 2000,
    retryAttempts: 2,
    retryDelay: 500,
  },
  features: {
    enableDebugMode: false,
    enablePerformanceMonitoring: true,
    enableStatePersistence: true,
    enableAutoSave: true,
    maxConcurrentRequests: 3,
    cacheEnabled: true,
    cacheTTL: 600000,
    optimisticUpdates: true,
  },
  auth: {
    tokenKey: 'auth_token_prod',
    refreshTokenKey: 'refresh_token_prod',
    sessionKey: 'user_session_prod',
    tokenExpirationBuffer: 600000,
    autoRefreshEnabled: true,
    sessionTimeout: 3600000,
  },
  logging: {
    level: 'error',
    enableConsole: false,
    enableRemote: true,
    remoteEndpoint: 'https://logs.portalautogestion.com/api/v1/logs',
    logActions: false,
    logStateChanges: false,
    logHttpRequests: false,
    logPerformanceMetrics: true,
  },
  performance: {
    enableWebVitals: true,
    reportInterval: 10000,
    metricsToTrack: ['LCP', 'FID', 'CLS'],
    maxMetricsBuffer: 100,
    enableLongTaskDetection: true,
    longTaskThreshold: 100,
  },
  state: {
    persistenceKey: 'portal_state_prod',
    blacklist: ['router', 'loading', 'debug'],
    whitelist: ['auth', 'profile', 'transaction'],
    syncInterval: 300000,
    enableDevTools: false,
    maxHistorySize: 20,
  },
  user: {
    maxActiveUsers: 10000,
    sessionWarningTime: 180000,
    idleTimeout: 600000,
    maxLoginAttempts: 3,
    lockoutDuration: 1800000,
  },
  ui: {
    theme: 'light',
    language: 'es',
    currency: 'COP',
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandSeparator: '.',
  },
  security: {
    enableCsrfProtection: true,
    enableXssProtection: true,
    enableContentSecurityPolicy: true,
    allowedDomains: ['api.portalautogestion.com', 'portalautogestion.com'],
  },
  analytics: {
    enabled: true,
    trackPageViews: true,
    trackEvents: true,
    trackErrors: true,
    sampleRate: 10,
  },
  errorHandling: {
    showDetailedErrors: false,
    enableErrorBoundary: true,
    maxRetries: 2,
    retryableStatusCodes: [408, 429, 502, 503, 504],
    fallbackMessage: 'Ha ocurrido un error inesperado. Por favor, intente más tarde.',
  },
  notifications: {
    enabled: true,
    position: 'top-right',
    duration: 4000,
    maxVisible: 3,
    types: {
      success: { duration: 2500, icon: true },
      error: { duration: 6000, icon: true },
      warning: { duration: 4000, icon: true },
      info: { duration: 3000, icon: true },
    },
  },
};

export type EnvironmentConfig = typeof environment;